@base_address = http://localhost:5200
GET {{base_address}}/api/users
###
POST {{base_address}}/api/users
Content-Type: application/json

{
  "passportNumber": "763890922",
  "surename": "Ivanov",
  "name": "Ivan",
  "dateOfBirth": "1999-07-15T00:00:00Z",
  "dateOfPassportExpiry": "2024-12-15T00:00:00Z"      
}
###
GET {{base_address}}/api/users/963890450
###
GET {{base_address}}/api/users/763890922
###
GET {{base_address}}/api/users/763890932