@base_address = http://localhost:5200
GET {{base_address}}/api/users
###
POST {{base_address}}/api/users
Content-Type: application/json

{
  "passportNumber": "129265038",
  "surename": "Klop",
  "name": "Mat",
  "dateOfBirth": "1989-04-25T00:00:00Z",
  "dateOfPassportExpiry": "2024-10-21T00:00:00Z"      
}
###
GET {{base_address}}/api/users/963890450
###
GET {{base_address}}/api/users/763890932
###
GET {{base_address}}/api/users/129265038